services:
  discovery-server:
    build: ./discovery-server/discovery-server
    ports:
      - "8761:8761"

  postgres-user-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service/user-service
    ports:
      - "9001:9001"
    depends_on:
      postgres-user-db:
        condition: service_healthy
      discovery-server:
        condition: service_started

  postgres-order-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ./order-service/order-service
    ports:
      - "9002:9002"
    depends_on:
      postgres-order-db:
        condition: service_healthy
      user-service:
        condition: service_started
      discovery-server:
        condition: service_started


  postgres-product-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5434:5432" # Ánh xạ ra một cổng khác trên máy host
    volumes:
      - product-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Thêm vào phần 'services'
  product-service:
    build: ./product-service/product-service # Giả sử thư mục code của bạn là 'product-service'
    ports:
      - "9003:9003"
    depends_on:
      postgres-product-db:
        condition: service_healthy
      discovery-server:
        condition: service_started

  api-gateway:
    build: ./api-gateway/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      order-service:
        condition: service_started
      user-service:
        condition: service_started
      discovery-server:
        condition: service_started

volumes:
  user-db-data:
  order-db-data:
  product-db-data: